<?php

namespace App\Filament\Resources\Translations\Pages;

use App\Filament\Resources\Translations\TranslationResource;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;

class EditTranslation extends EditRecord
{
    protected static string $resource = TranslationResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Tarjimani tahrirlash"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }
}
